/* The match: everything a game session owns, apart from the platform
 * that runs it (docs/ENGINE_ARCHITECTURE.md, loop extraction stage 1).
 *
 * GENERATED by scripts/codemod/session_stage1.py from platform_android.c's
 * hta_android. To add session state, add the field to HTA_SESSION_FIELDS
 * here; to add Android-only state, add it to hta_android after the union.
 *
 * The fields are a macro because hta_android still carries them in an
 * anonymous struct beside `hta_session session` (a union: one layout, two
 * spellings), so the Android loop's `s->game` keeps working while new,
 * portable code takes `hta_session *`. Stage 5 retires the macro.
 *
 * Portable: no Android header may be included here (tests/test_session.c
 * compiles this on the host to keep it so). */
#ifndef HTA_APP_SESSION_H
#define HTA_APP_SESSION_H

#include <stdatomic.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "../engine/engine.h"
#include "../engine/camera.h"
#include "../engine/player.h"
#include "../engine/gun.h"
#include "../engine/projectile.h"
#include "../engine/particle.h"
#include "../engine/vitals.h"
#include "../engine/actor.h"
#include "../engine/pickup.h"
#include "../engine/bot.h"
#include "../engine/vehicle.h"
#include "../engine/contrail.h"
#include "../engine/shake.h"
#include "../engine/ammo.h"
#include "../engine/hud.h"
#include "../engine/viewmodel.h"
#include "../engine/audio.h"
#include "../asset/dialogue.h"
#include "../asset/cache.h"
#include "../asset/bsp.h"
#include "../asset/bitmap.h"
#include "../asset/biped.h"
#include "../asset/weapon.h"
#include "../asset/sound.h"
#include "../asset/effect.h"
#include "../asset/model.h"
#include "../asset/items.h"
#include "../asset/strings.h"
#include "../asset/external_map.h"
#include "../asset/oal_asset.h"
#include "../gfx/gfx.h"
#include "../gfx/gfx_settings.h"
#include "../net/session.h"
#include "../net/replication.h"
#include "../game/game.h"
#include "../game/view.h"
#include "../game/nav.h"
#include "../game/menu.h"
#include "../game/external_world.h"
#include "../game/imported.h"
#include "../game/world_fx.h"
#include "../game/world_fx_audio.h"
#include "../game/world_fx_gpu.h"
#include "report.h"

#define HTA_SND_MAX_BANK  192u
#define HTA_SND_MAX_PERMS   8u
#define HTA_MAX_IMPORTED 32
#define HTA_ITEMS_UPLOAD_FRAMES 8

#define HTA_SESSION_FIELDS \
    /* asset state */                                                                          \
    char      map_path[512];                                                                   \
    char      bitmaps_path[512];                                                               \
    char      sounds_path[512];                                                                \
    uint8_t  *map_data;                                                                        \
    size_t    map_size;                                                                        \
    uint8_t  *bitmaps_data;                                                                    \
    size_t    bitmaps_size;                                                                    \
    uint8_t  *sounds_data;                                                                     \
    size_t    sounds_size;                                                                     \
    bool      map_loaded;                                                                      \
    bool      explore_external;                                                                \
    /* The match's world: "" is Blood Gulch; otherwise an imported map --                      \
     * "imported" is the package picked in Settings, any other name one                        \
     * built into the APK as assets/maps/<name>.oalmap. Its starts are kept                    \
     * for the game; everything else of Halo's still comes from the Trial. */                  \
    char      world[48];                                                                       \
    hta_external_map world_ext;                                                                \
    uint8_t  *world_playable;   /* nav nodes reachable from a start and back */                \
    bool      world_loaded;                                                                    \
    char      status[256];                                                                     \
                                                                                               \
    hta_cache     cache;                                                                       \
    hta_bsp_mesh  mesh;                                                                        \
    hta_bsp_mesh  sky;                                                                         \
    hta_bsp_mesh  coll_mesh;                                                                   \
    hta_viewmodel vm;                                                                          \
    hta_collision col;                                                                         \
    hta_vehicles vehicles;                                                                     \
    /* One static mesh per vehicle type, drawn as rigid parts. */                              \
    hta_gfx_mesh *gpu_vtypes[HTA_VEHICLE_TYPES];                                               \
    int           vehicle_roster;     /* HTA_VROSTER_*, from the match setup */                \
    int32_t       my_car, my_seat;    /* where this player sits, -1 on foot */                 \
    float         seat_look[2];       /* a Warthog driver's look, relative to the hull */      \
    bool          hud_alt;            /* the vehicle's second trigger, held */                 \
    bool          hud_jump, hud_fire, hud_crouch; /* held, latched (app/input.c) */            \
    bool          veh_fire;           /* the vehicle gun's trigger, for the host */            \
    bool          show_self;          /* our own body is on screen: third person */            \
    uint16_t      net_action_count, net_ability_count;                                         \
    uint16_t      peer_ability_seen[8];                                                        \
    uint16_t      peer_action_seen[8];                                                         \
    /* A joiner in a custom-class game stays out until it says READY. */                       \
    bool          peer_ready[8];                                                               \
    bool          peer_class_reject[8];                                                        \
    uint32_t      vehicles_applied_tick;                                                       \
    uint32_t      game_applied_tick;                                                           \
    double        vsnap_time;                                                                  \
    hta_net_vehicle vfrom[HTA_VEHICLE_MAX], vto[HTA_VEHICLE_MAX];                              \
    bool          vhave[HTA_VEHICLE_MAX];                                                      \
    uint32_t      veh_in_snd, veh_out_snd;                                                     \
    uint32_t      veh_engine[HTA_VEHICLE_TYPES];   /* each type's engine `snd!` */             \
    float         veh_engine_gain[HTA_VEHICLE_TYPES];                                          \
    bool          veh_engine_on[HTA_VEHICLE_MAX];                                              \
    uint32_t      vfire_recipe[HTA_GAME_MAX_WEAPONS];                                          \
    /* Tracers and trails, from each round's own contrail tag. */                              \
    hta_contrails trails;                                                                      \
    hta_gfx_mesh *gpu_trails;                                                                  \
    uint32_t      wtrail[HTA_GAME_MAX_WEAPONS], ptrail[HTA_GAME_MAX_POOLS], laser_trail;       \
    uint32_t hero_trail[6], hero_ring[6], hero_core, hero_sound[6], flight_clip;               \
    float hero_sound_time[HTA_GAME_MAX_UNITS];                                                 \
    float hero_bark_time[HTA_GAME_MAX_UNITS];                                                  \
    const char *bark_name[12];                                                                 \
    uint32_t bark_clip[12];                                                                    \
    int bark_count;                                                                            \
    hta_gfx_mesh *gpu_gibs;                                                                    \
    /* Rounds each shooter has fired since its last tracer (the trigger's                      \
     * `projectiles between contrails`); the last slot is ours on foot. */                     \
    uint8_t       since_tracer[HTA_GAME_MAX_UNITS + 1];                                        \
    /* The view thrown about by blasts and by our own gun's kick. */                           \
    hta_shake     shake;                                                                       \
    uint32_t      local_trail;     /* the held weapon's flying round */                        \
                                                                                               \
    /* Sound. One bank entry per snd! tag actually asked for, decoded once and                 \
     * kept; Halo tags carry several permutations of the same sound and pick                   \
     * between them, so each entry holds every permutation as its own clip. */                 \
    hta_resource_map sounds_rm;                                                                \
    hta_resource_map bitmaps_rm;                                                               \
    hta_audio        audio;                                                                    \
    bool             audio_ok;                                                                 \
    struct {                                                                                   \
        uint32_t tag_id;                                                                       \
        uint32_t count;                                                                        \
        uint32_t clip[HTA_SND_MAX_PERMS];                                                      \
        int16_t *pcm[HTA_SND_MAX_PERMS];                                                       \
    } bank[HTA_SND_MAX_BANK];                                                                  \
    uint32_t bank_count;                                                                       \
    uint32_t fire_snd;       /* snd! id of the weapon's gunshot, 0 if none */                  \
    /* A weapon whose firing effect has no sound at all roars continuously                     \
     * instead: the flamethrower. Held for as long as the trigger is. */                       \
    uint32_t fire_loop_snd;                                                                    \
    float    fire_loop_gain;                                                                   \
    bool     fire_loop_on;                                                                     \
    /* And the same weapon sprays rather than shoots: the flamethrower's jet                   \
     * is a `pctl` particle system attached to its `spawn fire` marker,                        \
     * emitted for as long as the trigger is held rather than burst. */                        \
    uint32_t jet_recipe;                                                                       \
    uint32_t empty_snd;      /* the click when the magazine is out */                          \
    uint32_t foot_snd[33];   /* per MaterialType, resolved on first use */                     \
    uint8_t  foot_known[33];                                                                   \
    uint32_t impact_snd[33];                                                                   \
    uint8_t  impact_known[33];                                                                 \
                                                                                               \
    /* Every weapon in the cache a player could hold, and which one is up. */                  \
    /* Every weapon the cache has, kept only so a missing loadout has                          \
     * something to fall back on. What you are actually CARRYING is `held`. */                 \
    uint32_t weapons[24];                                                                      \
    uint32_t weapon_count;                                                                     \
    /* Two, because the scenario says two: its player starting profile has a                   \
     * primary weapon and a secondary and nowhere to put a third, and the                      \
     * map's starting equipment hands out exactly two collections. `held_slot`                 \
     * is the one in your hands. */                                                            \
    uint32_t held[HTA_CARRY_MAX];                                                              \
    /* What is in the gun NOT in hand. The one in hand is `ammo`; switching                    \
     * used to re-init it from the tag, which refilled it for free. */                         \
    hta_ammo held_ammo[HTA_CARRY_MAX];                                                         \
    bool     held_ammo_set[HTA_CARRY_MAX];                                                     \
    uint32_t held_count;                                                                       \
    uint32_t held_slot;                                                                        \
    uint32_t start_weapon[HTA_CARRY_MAX];                                                      \
    uint32_t start_count;                                                                      \
    /* Imported weapons ride on a Halo weapon's tag, so a slot's tag alone                     \
     * cannot tell an AK-47 from the assault rifle under it: this is the                       \
     * roster index of an imported weapon in that slot, -1 otherwise. */                       \
    int32_t  held_asset[HTA_CARRY_MAX];                                                        \
    int32_t  start_asset[HTA_CARRY_MAX];                                                       \
                                                                                               \
    /* Imported content built into the APK (assets/characters and                              \
     * assets/weapons): loaded once, for the menus and every match. */                         \
    hta_oal_asset imp_char[HTA_MAX_IMPORTED];                                                  \
    uint32_t imp_char_count;                                                                   \
    uint32_t imp_voice[HTA_MAX_IMPORTED][2]; /* authored hurt/death clips */                   \
    float character_voice_time[HTA_GAME_MAX_UNITS];                                            \
    hta_oal_asset imp_weap[HTA_MAX_IMPORTED];                                                  \
    uint32_t imp_weap_count;                                                                   \
    uint32_t imp_clip[HTA_MAX_IMPORTED][2];      /* audio: fire, reload */                     \
    bool     imported_loaded;                                                                  \
    /* This match's look and class, from the menus. */                                         \
    char     my_character[48];                                                                 \
    bool     bots_imported;                                                                    \
    bool     classes;                                                                          \
    char     my_class[2][48];                                                                  \
    /* Hit feedback: a ding when your shot lands, a louder one for a kill                      \
     * (TF2's own from the sound pack, else synthesized), and the damage                       \
     * floating up off whoever took it. */                                                     \
    hta_oal_asset ui_sounds;                                                                   \
    uint32_t ding_clip, kill_clip, freeze_clip, snap_clip;                                     \
    /* The killcam: after the fall, the view swoops to whoever killed you,                     \
     * zooming, and holds a still frame (TF2's freeze cam). */                                 \
    int32_t  killcam_unit;      /* -1: none (no killer, or yourself) */                        \
    int      killcam_phase;     /* 0 waiting, 1 swooping, 2 frozen */                          \
    float    killcam_from[3];                                                                  \
    float    killcam_fov;       /* the view's own, to zoom from */                             \
    char     killcam_weapon[48];                                                               \
    hta_camera killcam_cam;     /* the frozen view, held until the fade */                     \
    /* The class screen's character preview: which body and weapon are up,                     \
     * their GPU copies, the posed body and how long it has turned. */                         \
    int32_t  prev_char, prev_weap, prev_roster;                                                \
    int32_t  next_character;    /* a class's body for the next respawn; -2 none */             \
    bool     power_fly;         /* flying by yourself (FLY): Goku, Superman */                 \
    bool     allow_duplicate_heroes;  /* custom match rule */                                  \
    hta_gfx_mesh *gpu_prev_body, *gpu_prev_weap;                                               \
    hta_vertex *prev_posed;                                                                    \
    uint32_t prev_cap;                                                                         \
    float    prev_height, prev_time;                                                           \
    float    prev_world[HTA_OAL_MAX_BONES][12];                                                \
    float    ding_cool;         /* one ding per volley, not per pellet */                      \
    struct { float pos[3]; float amount, age; int32_t victim; } dmg[16];                       \
    /* A custom-class match holds you out of it until you have picked. */                      \
    bool     choosing;                                                                         \
    int      selected_team; /* -1 until the joining player chooses */                          \
    float    spawn_protect;     /* seconds, from the match setup */                            \
    /* The first-person view of an imported weapon. */                                         \
    hta_gfx_mesh *gpu_ivm;                                                                     \
    int32_t  ivm_weapon;        /* roster index it was uploaded for, -1 */                     \
    const char *ivm_role;       /* the clip wanted: "idle", "fire", "reload", "draw" */        \
    int32_t  ivm_clip;                                                                         \
    float    ivm_time;                                                                         \
    float    ivm_rate;          /* clip seconds per real second (a reload fitted to its time) */ \
    /* Sway: the view lags the look a little and bobs with the walk. */                        \
    float    ivm_lag[2];        /* yaw, pitch, radians */                                      \
    float    ivm_last[2];       /* last frame's camera yaw, pitch */                           \
    float    ivm_bob;           /* walk phase */                                               \
    hta_vertex *ivm_posed;                                                                     \
    uint32_t ivm_cap;                                                                          \
    float    ivm_world[HTA_OAL_MAX_BONES][12];                                                 \
    bool     hud_swap;                                                                         \
    bool     hud_zoom;                                                                         \
    int      zoom_level;     /* 0 = not zoomed */                                              \
    float    base_fov;                                                                         \
    bool     bitmaps_ok;                                                                       \
    uint32_t rng;                                                                              \
                                                                                               \
    /* Rounds you can watch fly: the rocket and the needle. */                                 \
    hta_projectiles proj;                                                                      \
    /* And the grenades, which come from the globals table rather than                         \
     * from anything you are holding. */                                                       \
    hta_projectiles nades;                                                                     \
    hta_gfx_mesh   *gpu_nades;                                                                 \
    uint32_t        nade_recipe;                                                               \
    uint32_t        nade_snd;                                                                  \
    int             nade_count;                                                                \
    int             nade_max;                                                                  \
    /* And the smoke and fire their detonation throws out, plus the dust a                     \
     * bullet kicks up. Blood Gulch is made of four materials, so four                         \
     * impact effects cover every surface a round can land on. */                              \
    hta_particles   parts;                                                                     \
    uint32_t        det_recipe;                                                                \
    uint32_t        casing_recipe;                                                             \
    uint32_t        impact_recipe[33];                                                         \
    uint8_t         map_material[33];      /* the ones this map contains */                    \
    uint32_t        map_material_count;                                                        \
                                                                                               \
    /* The game: Slayer against bots, everyone's damage attributed. The                        \
     * local player is unit `me`, mirrored in every frame; the bots live                       \
     * entirely inside it and are drawn from `gview`. */                                       \
    /* The main menu: ui.map's ring and sky, the HALO logo and the shell's                     \
     * words, before any level is loaded. */                                                   \
    bool          menu_mode;                                                                   \
    hta_menu      menu;                                                                        \
    hta_cache     ui_cache;                                                                    \
    uint8_t      *ui_data;                                                                     \
    size_t        ui_size;                                                                     \
    hta_gfx_mesh *gpu_menu_scene, *gpu_menu_sky, *gpu_menu_ui;                                 \
    int           menu_pressed;                                                                \
    bool          menu_go;           /* MULTIPLAYER was chosen: load the level */              \
    uint32_t      menu_clip[3];      /* cursor, forward, back */                               \
    uint32_t      music_in, music_loop;                                                        \
    float         music_left;        /* seconds of the intro still playing */                  \
    bool          music_looping;                                                               \
    int16_t      *menu_pcm[8];                                                                 \
    uint32_t      menu_pcm_count;                                                              \
                                                                                               \
    hta_game      game;                                                                        \
    hta_game_view gview;                                                                       \
    hta_nav       nav;                                                                         \
    bool          game_on;                                                                     \
    int32_t       me;                                                                          \
    int           bot_count, bot_skill;                                                        \
    /* The match the menu set up: kills to win (0 leaves the game's                            \
     * default), minutes of play (0 none), seconds to come back. */                            \
    int           score_limit, time_limit_min;                                                 \
    float         respawn_delay;                                                               \
    int           game_mode;       /* hta_game_mode the menu chose */                          \
    int8_t        carried_flag;    /* the flag this player held last frame, or -1 */           \
    uint32_t      flag_take_snd;                                                               \
    hta_gfx_mesh *gpu_units[HTA_GAME_MAX_UNITS];                                               \
    hta_gfx_mesh *gpu_held[HTA_GAME_MAX_WEAPONS];                                              \
    int8_t   gpu_unit_char[HTA_GAME_MAX_UNITS];   /* which body gpu_units[i] holds */          \
    hta_gfx_mesh *gpu_pools[HTA_GAME_MAX_POOLS];                                               \
    uint32_t      pool_recipe[HTA_GAME_MAX_POOLS];                                             \
    /* A vehicle going up, and sparks off a hull that is nearly gone. */                       \
    uint32_t      wreck_recipe, wreck_snd, spark_recipe;                                       \
    float         spark_clock;                                                                 \
    uint32_t      unit_fire_snd[HTA_GAME_MAX_WEAPONS];                                         \
    uint8_t       unit_fire_known[HTA_GAME_MAX_WEAPONS];                                       \
    uint32_t      line_snd[HTA_LINE_COUNT];                                                    \
    char          feed[4][96];                                                                 \
    float         feed_age[4];                                                                 \
    char          banner[96];                                                                  \
    float         banner_age;                                                                  \
    char          item_msg[96];      /* "Picked up a rocket launcher" */                       \
    float         item_msg_age;                                                                \
    float         over_timer;                                                                  \
                                                                                               \
    /* Health and shield, and what takes them away. `vit` points at these                      \
     * until the game starts, then at the game's own copy for this player,                     \
     * so a bot's round and the local HUD read the same numbers. */                            \
    hta_vitals vitals;                                                                         \
    hta_vitals *vit;                                                                           \
                                                                                               \
    /* Dying. Halo's multiplayer respawn is five seconds; that number is the                   \
     * gametype's, and no gametype ships in the map, so it is ours. The rest                   \
     * is the tag's: the Chief has a quiet death and a violent one, and                        \
     * which you get depends on what killed you. */                                            \
    bool     dead;                                                                             \
    float    damage_flash_left;                                                                \
    float    dead_timer;        /* seconds until the respawn */                                \
    float    death_pos[3];      /* where it happened, so we come back elsewhere */             \
    uint32_t death_quiet_snd, death_violent_snd, death_falling_snd;                            \
    /* The shield's own voice, from the unit HUD tag. */                                       \
    uint32_t shield_charge_snd, shield_hit_snd, shield_low_snd;                                \
    uint32_t shield_empty_snd, health_low_snd;                                                 \
    bool     shield_charge_on, shield_low_on, health_low_on;                                   \
    uint32_t spawn_rng;                                                                        \
    hta_spawn_point spawn[64];                                                                 \
    uint32_t spawn_count;                                                                      \
    /* Your own body, for looking at from outside. The only third-person                       \
     * thing in the game so far. */                                                            \
    hta_actor     corpse;                                                                      \
    hta_gfx_mesh *gpu_corpse;                                                                  \
    bool          corpse_up;                                                                   \
                                                                                               \
    /* What the map leaves on the ground. */                                                   \
    hta_pickups   items;                                                                       \
    hta_gfx_mesh *gpu_items;                                                                   \
    /* Frames left to keep uploading the item geometry. The dynamic path                       \
     * writes one vertex slot per in-flight frame, so a single change has to                   \
     * reach every one of them before it can stop -- and how many there are                    \
     * is the swapchain's image count, which is not ours to know. Eight                        \
     * covers any of them; the cost of a few extra copies after something is                   \
     * picked up is nothing beside doing it every frame forever. */                            \
    int           items_upload;                                                                \
    uint32_t      pickup_snd_health, pickup_snd_shield, pickup_snd_camo;                       \
    uint32_t      pickup_snd_ammo;                                                             \
    float         powerup_timer;                                                               \
    hta_item_kind powerup;                                                                     \
    bool          throwing;      /* the arm is mid-throw-grenade */                            \
    /* The DBG pad, as (action + 1) so zero means nothing pending. Blood                       \
     * Gulch places neither the needler nor the plasma pistol, so playing                      \
     * the map honestly puts them out of reach; this is the way back to                        \
     * them, and the place to hang the next debug thing off. */                                \
    int           hud_debug;                                                                   \
    uint32_t      debug_weapon;  /* where the roster walk has got to */                        \
                                                                                               \
    /* Somebody to shoot at. One for now, and the reason melee, grenades and                   \
     * every weapon can be said to work at all. */                                             \
    hta_bot       bot;                                                                         \
    hta_gfx_mesh *gpu_bot;                                                                     \
    /* First LAN slice: one other live Spartan, using the same world actor                     \
     * path as the corpse and target bot. Multiple remote meshes come later. */                \
    hta_actor     remote[2]; /* map starting AR and pistol slots */                            \
    hta_gfx_mesh *gpu_remote[2];                                                               \
    hta_net_client net;                                                                        \
    hta_net_server host_server;                                                                \
    bool          net_hosting;                                                                 \
    bool          net_enabled, remote_visible;                                                 \
    uint8_t       remote_id;                                                                   \
    hta_net_player remote_from, remote_to;                                                     \
    double        remote_snapshot_time, net_last_send;                                         \
    uint64_t      net_last_snapshots;                                                          \
    uint32_t      net_event_id;                                                                \
    int8_t        peer_unit[HTA_NET_MAX_PLAYERS];                                              \
    uint16_t      peer_melee_seen[HTA_NET_MAX_PLAYERS];                                        \
    uint16_t      peer_grenade_seen[HTA_NET_MAX_PLAYERS];                                      \
    uint16_t      peer_reload_seen[HTA_NET_MAX_PLAYERS];                                       \
    uint16_t      peer_pickup_seen[HTA_NET_MAX_PLAYERS];                                       \
    uint16_t      net_melee_count, net_grenade_count, net_reload_count, net_pickup_count;      \
    hta_net_control net_control;                                                               \
    uint16_t      world_round;                                                                 \
    uint32_t      world_applied_tick;                                                          \
    uint32_t      projectile_applied_tick;                                                     \
    bool          world_local_bound;                                                           \
    hta_net_stats net_stats_prev;                                                              \
    double        remote_action_until;                                                         \
    bool          net_spawned;                                                                 \
    uint32_t      impact_jpt;    /* the held weapon's own damage tag */                        \
    float         melee_damage;  /* the cyborg's, 1000 -- see the handoff */                   \
                                                                                               \
    hta_ammo ammo;                                                                             \
    float    dry_cooldown;   /* stops an empty trigger clicking every frame */                 \
    bool     hud_reload;                                                                       \
    bool     hud_melee;                                                                        \
    bool     hud_fly;                                                                          \
    bool     hud_ability;                                                                      \
    bool     hud_grenade;                                                                      \
    bool          have_mesh;                                                                   \
    bool          have_sky;                                                                    \
    bool          have_coll;                                                                   \
    bool          have_fp;                                                                     \
    hta_weapon_def weap;                                                                       \
                                                                                               \
    /* runtime */                                                                              \
    hta_gfx      *gfx;                                                                         \
    hta_gfx_mesh *gpu_mesh;                                                                    \
    hta_gfx_mesh *gpu_sky;                                                                     \
    hta_gfx_mesh *gpu_fx;                                                                      \
    hta_gfx_mesh *gpu_proj;                                                                    \
    hta_gfx_mesh *gpu_parts;                                                                   \
    hta_gfx_mesh *gpu_fp;                                                                      \
    hta_hud       hud;                                                                         \
    hta_gfx_mesh *gpu_hud;                                                                     \
    hta_camera    cam;                                                                         \
    hta_player    player;                                                                      \
    hta_gun       gun;                                                                         \
    hta_scene     scene;                                                                       \
    double        last_time;                                                                   \
    uint64_t      frames;                                                                      \
    double        fps_accum;                                                                   \
    uint32_t      fps_frames;                                                                  \
                                                                                               \
    /* Video settings (SETTINGS writes video.cfg; gfx_settings.c reads                         \
     * it) and the world-effects director: debris, gibs, splats, weather. */                   \
    hta_gfx_settings video;                                                                    \
    bool    video_loaded, video_auto;                                                          \
    char    video_cfg[2048];                                                                   \
    size_t  video_cfg_len;                                                                     \
    hta_world_fx wfx;                                                                          \
    const void *wfx_world;            /* the mesh it was set up for */                         \
    hta_wfx_audio wfx_audio;          /* procedural sounds for props, debris, gibs, weather */ \
    hta_instance_index col_index;     /* broad phase over col_merged, rebuilt each frame */    \
    bool props_synced, props_count_warned;   /* LAN client: host's props applied */            \
    /* Vehicles' collision instances and the props', merged every frame                        \
     * into the one list the world grid points at. */                                          \
    hta_collision_instance col_merged[HTA_VEHICLE_MAX + 256];                                  \
    /* Diagnostics (app/report.h): frame times for the report, and when                        \
     * the session began. */                                                                   \
    hta_frame_stats frame_stats;                                                               \
    double        started_at;                                                                  \

typedef struct hta_session {
    HTA_SESSION_FIELDS
} hta_session;

#endif
