#!/usr/bin/env python3
"""Loop extraction, stage 1 (docs/ENGINE_ARCHITECTURE.md): the match's state
out of `hta_android` into `hta_session` (src/app/session.h), with NO change
to the ~2800 `s->field` / `state.field` uses.

`hta_android` keeps the session's fields in an anonymous struct unioned
with a named `hta_session session`: the same fields, the same layout, so
old code still reads `s->game` and new code can take `&s->session`.

Idempotent and re-runnable: it reads the current struct, so fields a local
session has added since are carried over. Fields named in ANDROID stay in
hta_android; every other field moves. Run it, then scripts/ndkcheck.sh.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / 'src/platform/platform_android.c'
HDR = ROOT / 'src/app/session.h'

# What is Android's: the app, APK mappings, the window, touch and the Java
# HUD's raw buttons (stage 2 turns those into hta_input).
ANDROID = {
    'app', 'mapped_base', 'mapped_len', 'mapped_count',
    'has_window', 'win_w', 'win_h', 'probe_done',
    'move_pointer', 'look_pointer', 'move_origin', 'move_cur', 'look_last',
    'pad_move', 'pad_look', 'jump_held', 'fire_held', 'pad_fire',
    'pending_yaw', 'pending_pitch',
    'hud_ready', 'hud_move', 'hud_jump', 'hud_fire', 'hud_crouch',
}

HEADER_TOP = '''/* The match: everything a game session owns, apart from the platform
 * that runs it (docs/ENGINE_ARCHITECTURE.md, loop extraction stage 1).
 *
 * GENERATED by scripts/codemod/session_stage1.py from platform_android.c's
 * hta_android. To add session state, add the field to HTA_SESSION_FIELDS
 * here; to add Android-only state, add it to hta_android after the union.
 *
 * The fields are a macro because hta_android still carries them in an
 * anonymous struct beside `hta_session session` (a union: one layout, two
 * spellings), so the Android loop's `s->game` keeps working while new,
 * portable code takes `hta_session *`. Stage 5 retires the macro.
 *
 * Portable: no Android header may be included here (tests/test_session.c
 * compiles this on the host to keep it so). */
#ifndef HTA_APP_SESSION_H
#define HTA_APP_SESSION_H

#include <stdatomic.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "../engine/engine.h"
#include "../engine/camera.h"
#include "../engine/player.h"
#include "../engine/gun.h"
#include "../engine/projectile.h"
#include "../engine/particle.h"
#include "../engine/vitals.h"
#include "../engine/actor.h"
#include "../engine/pickup.h"
#include "../engine/bot.h"
#include "../engine/vehicle.h"
#include "../engine/contrail.h"
#include "../engine/shake.h"
#include "../engine/ammo.h"
#include "../engine/hud.h"
#include "../engine/viewmodel.h"
#include "../engine/audio.h"
#include "../asset/dialogue.h"
#include "../asset/cache.h"
#include "../asset/bsp.h"
#include "../asset/bitmap.h"
#include "../asset/biped.h"
#include "../asset/weapon.h"
#include "../asset/sound.h"
#include "../asset/effect.h"
#include "../asset/model.h"
#include "../asset/items.h"
#include "../asset/strings.h"
#include "../asset/external_map.h"
#include "../asset/oal_asset.h"
#include "../gfx/gfx.h"
#include "../gfx/gfx_settings.h"
#include "../net/session.h"
#include "../net/replication.h"
#include "../game/game.h"
#include "../game/view.h"
#include "../game/nav.h"
#include "../game/menu.h"
#include "../game/external_world.h"
#include "../game/imported.h"
#include "../game/world_fx.h"
#include "../game/world_fx_audio.h"
#include "../game/world_fx_gpu.h"

'''


# Defines above the struct that its fields use: they move with the fields.
MOVE_DEFINES = ('HTA_SND_MAX_BANK', 'HTA_SND_MAX_PERMS')


def main():
    src = SRC.read_text()
    moved = []
    for name in MOVE_DEFINES:
        dm = re.search(r'\n(#define ' + name + r'\b[^\n]*)\n', src)
        if dm:
            moved.append(dm.group(1).strip())
            src = src[:dm.start()] + '\n' + src[dm.end():]
    m = re.search(r'\ntypedef struct \{\n(.*?)\n\} hta_android;\n', src, re.S)
    if not m:
        sys.exit('hta_android not found')
    body = m.group(1)
    if 'HTA_SESSION_FIELDS' in body:
        body = unfold(src, body)
    # Split the body into declarations (with the comments above them) and
    # preprocessor lines, which cannot live inside a macro.
    defines, session, android = [], [], []
    pending = []
    depth = 0
    decl = []
    for line in body.split('\n'):
        s = line.strip()
        if s.startswith('#'):
            defines.append(s)
            continue
        if depth == 0 and not decl and (not s or s.startswith('/*') or s.startswith('*')):
            pending.append(line)
            continue
        decl.append(line)
        depth += line.count('{') - line.count('}')
        code = re.sub(r'/\*.*?\*/', '', s).strip()
        if depth == 0 and code.endswith(';'):
            text = '\n'.join(decl)
            names = declared_names(text)
            dest = android if names and names <= ANDROID else session
            if names & ANDROID and not names <= ANDROID:
                sys.exit(f'mixed declaration, split it by hand: {text.strip()}')
            dest.extend(pending + decl)
            pending, decl = [], []
    session.extend(pending)
    fields = '\n'.join(l.rstrip() for l in session).strip('\n')
    macro_lines = [(l + ' ' * max(1, 95 - len(l)) + '\\') for l in fields.split('\n')]
    defines = moved + [d for d in defines if d not in moved]
    header = (HEADER_TOP + '\n'.join(defines) + '\n\n#define HTA_SESSION_FIELDS \\\n' +
              '\n'.join(macro_lines) + '\n\ntypedef struct hta_session {\n    HTA_SESSION_FIELDS\n} hta_session;\n\n#endif\n')
    HDR.parent.mkdir(parents=True, exist_ok=True)
    HDR.write_text(header)
    android_body = '\n'.join(android).strip('\n')
    new = ('\ntypedef struct {\n'
           '    /* The match (src/app/session.h): read as s->game here, or whole as\n'
           '     * s->session by code that must not know it runs on Android. */\n'
           '    union {\n        struct { HTA_SESSION_FIELDS };\n        hta_session session;\n    };\n\n'
           '    /* Android\'s own: the app, APK mappings, the window, touch. */\n' +
           android_body + '\n} hta_android;\n'
           '_Static_assert(offsetof(hta_android, game) == offsetof(hta_android, session.game),\n'
           '               "hta_android\'s session fields and hta_session must share a layout");\n')
    rest = src[m.end():]
    ra = re.match(r'_Static_assert\(offsetof\(hta_android, game\).*?\);\n', rest, re.S)
    if ra:
        rest = rest[ra.end():]          # a re-run: replace, do not stack
    src = src[:m.start()] + new + rest
    for d in defines:            # they now live in session.h
        src = src.replace('\n' + d + '\n', '\n', 1) if src.count(d) > 1 else src
    if '#include "../app/session.h"' not in src:
        src = src.replace('#include "platform.h"\n', '#include "platform.h"\n#include "../app/session.h"\n', 1)
    SRC.write_text(src)
    print(f'session fields: {len(session)} lines; android: {len(android)} lines; defines moved: {defines}')


def declared_names(text):
    """The field names a declaration declares (outside any nested braces)."""
    flat = re.sub(r'/\*.*?\*/', '', text, flags=re.S)
    while '{' in flat:
        flat = re.sub(r'\{[^{}]*\}', '', flat)
    flat = flat.strip().rstrip(';')
    names = set()
    # type ... a, *b, c[4]
    parts = flat.split(',')
    first = parts[0].split()
    if not first:
        return names
    names.add(re.sub(r'[\[\*].*', '', first[-1].lstrip('*')).strip())
    for p in parts[1:]:
        names.add(re.sub(r'\[.*', '', p.strip().lstrip('*')).strip())
    return {n for n in names if n}


def unfold(src, body):
    """Re-running after stage 1: rebuild the flat body from the header's
    macro plus hta_android's own fields."""
    hdr = HDR.read_text()
    mm = re.search(r'#define HTA_SESSION_FIELDS \\\n(.*?)\n\ntypedef struct hta_session', hdr, re.S)
    fields = '\n'.join(re.sub(r'\s*\\$', '', l) for l in mm.group(1).split('\n'))
    defines = [l for l in hdr.split('\n') if l.startswith('#define HTA_') and 'SESSION_FIELDS' not in l and 'APP_SESSION_H' not in l]
    own = body.split("/* Android's own: the app, APK mappings, the window, touch. */", 1)[1]
    return '\n'.join(defines) + '\n' + fields + '\n' + own


if __name__ == '__main__':
    main()
